<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * AnswerPointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerPointsRepository extends EntityRepository
{

	public function getPointsForCorrectAnswer()
	{
		$answerPoints = $this->findOneByName("correct");
		return $answerPoints->getPoints();
	}

	public function getPointsForIncorrectAnswer()
	{
		$answerPoints = $this->findOneByName("incorrect");
		return $answerPoints->getPoints();
	}
}
