<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GamificationPointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamificationTypeRepository extends EntityRepository
{
	/**
	 * Gets GamificationType badges Entity
	 *
	 * @return GamificatioType
	 */
	public function getBadgesEntity()
	{
		$badgesEntity = $this->findOneByName("badges");

		return $badgesEntity;
	}
	/**
	 * Gets GamificationType levels Entity
	 *
	 * @return GamificationType
	 */
	public function getLevelsEntity()
	{
		$levelsEntity = $this->findOneByName("levels");

		return $levelsEntity;
	}

	/**
	 * Gets GamificationType none Entity
	 *
	 * @return GamificationType
	 */
	public function getNoneEntity()
	{
		$levelsEntity = $this->findOneByName("none");

		return $levelsEntity;
	}
}