<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{

	/**
	 * Gets N random images
	 *
	 * @param integer	$quantity			number of images randombly selected
	 * @param integer	$quantityCorrect	number of correct images randombly selected
	 *
	 * @return array(\App\AppBundle\Entity\Image)
	 *
	 */
	public function getRandomImages($quantity=3,$quantityCorrect=1)
	{
		$correctImages 		= 	$this->getRandomCorrectImages($quantityCorrect);
		$quantityIncorrect	=	$quantity - $quantityCorrect;
		$incorrectImages	= 	$this->getRandomIncorrectImages($quantityIncorrect);

		$images = array_merge($correctImages,$incorrectImages);

		//randomize the merged array
		shuffle($images);
		return $images;
	}

	/**
	 * Gets N random correct images
	 *
	 * @param integer $quantity Number of images randombly selected
	 *
	 * @return array(\App\AppBundle\Entity\Image)
	 *
	 */
	public function getRandomCorrectImages($quantity)
	{
		$images = $this->findRandomImages($quantity,true);
		
		return $images;
	}

		/**
	 * Gets N random incorrect images
	 *
	 * @param integer $quantity Number of images randombly selected
	 *
	 * @return array(\App\AppBundle\Entity\Image)
	 *
	 */
	public function getRandomIncorrectImages($quantity)
	{
		$images = $this->findRandomImages($quantity,false);
		return $images;
	}

	public function findRandomImages($quantity,$shouldImagesBeCorrect)
	{
		//this could be very inefficient if there are many Images, use with caution!!
		//more options in:
		//http://stackoverflow.com/questions/10762538/how-to-select-randomly-with-doctrine
		//gets all the images 
		$images = $this->findByIsCorrect($shouldImagesBeCorrect);
		//shuffles the array
		shuffle($images);

		//returns the firsts $quantity images
		return array_slice($images,0,$quantity);
	}
}
