<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantSessionRepository extends EntityRepository
{
}
