<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantResponseRepository extends EntityRepository
{
}
