<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{

	/**
	 * Gets the amount of training tasks
	 *
	 * @param integer	$quantity			number of images randombly selected
	 * @param integer	$quantityCorrect	number of correct images randombly selected
	 *
	 * @return array(\App\AppBundle\Entity\Image)
	 *
	 */
	public function getMaxNumberOfQuestions()
	{
		$qb = $this->createQueryBuilder('t');
		$qb->select("count(t.id)");
		$query = $qb->getQuery();
		$numberTrainingTasks = $query->getSingleScalarResult();
		return $numberTrainingTasks;
	}

}